version: '2.3'
services: 
  conda:
    build: .
    image: katsu1110-probspace-realestate2
    container_name: katsu1110-probspace-realestate2-conda
    tty: true
    command: /bin/bash
    volumes: 
      - ./:/analysis
      - ${INPUT_DIR}:/analysis/input
      - ${OUTPUT_DIR}:/analysis/output
    env_file: .env